const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const assert=require('node:assert/strict');const fs=require('fs');
(async()=>{const b=await chromium.launch({...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {}),headless:true});const base=process.env.QA_URL||'http://127.0.0.1:8765';const routes=['/','/apps/','/apps/stockclearance/','/apps/tariffshield/','/apps/shelflife/','/apps/accessshield/','/apps/storechronicle/','/apps/warrantytracker/','/blog/','/blog/dead-stock-clearance-q2-2026/','/tools/','/duty/','/shipping/','/tools/access-checker/','/privacy','/terms','/contact','/analytics-preferences/'];let results=[];let failures=[];const p=await b.newPage();p.on('pageerror',e=>failures.push('JS: '+e.message));await p.route('**/*google-analytics.com/**',r=>r.abort());await p.route('**/*googletagmanager.com/**',r=>r.abort());for(const width of [1440,768,390,320]){await p.setViewportSize({width,height:900});for(const route of routes){const resp=await p.goto(base+route);if(resp.status()===404){failures.push('404 '+route);continue;}console.log('Checking',width,route);if(route==='/tools/access-checker/'){await p.waitForURL('https://accesschecker.attahirlabs.com/**',{waitUntil:'domcontentloaded'});await p.locator('h1').waitFor({state:'visible'});}await p.waitForTimeout(300);const result=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,h1:document.querySelectorAll('h1').length,main:!!document.querySelector('main,article,.container'),broken:[...document.querySelectorAll('img')].filter(i=>i.complete&&i.naturalWidth===0).map(i=>i.src)}));results.push({width,route,...result});if(result.overflow||result.h1!==1||result.broken.length)failures.push(JSON.stringify({width,route,...result}));}}
await p.setViewportSize({width:390,height:844});await p.goto(base+'/apps/shelflife/');await p.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Close',exact:true}).getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.getByRole('button',{name:'Menu',exact:true}).getAttribute('aria-expanded'),'false');
await p.locator('[data-step="1"]').click();assert.equal(await p.locator('[data-panel="1"]').isVisible(),true);await p.keyboard.press('ArrowDown');assert.equal(await p.locator('[data-panel="2"]').isVisible(),true);
await p.emulateMedia({reducedMotion:'reduce'});await p.goto(base+'/');await p.evaluate(()=>scrollTo(0,300));await p.waitForTimeout(100);assert.equal(await p.locator('.glass-artwork').evaluate(e=>getComputedStyle(e).animationName),'none');assert.equal(await p.locator('.glass-artwork').evaluate(e=>e.style.getPropertyValue('--depth')),'0.0px');
const nojs=await b.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const n=await nojs.newPage();await n.goto(base+'/apps/shelflife/');assert.equal(await n.locator('[data-panel]:visible').count(),3);assert.equal(await n.getByRole('link',{name:'All apps ↗',exact:true}).isVisible(),true);await nojs.close();
await p.emulateMedia({reducedMotion:'no-preference'});for(const [name,url,width]of [['home','/',1440],['shelflife','/apps/shelflife/',1440],['storechronicle','/apps/storechronicle/',1440],['blog','/blog/',1440],['mobile','/',390],['shelflife-mobile','/apps/shelflife/',390]]){await p.setViewportSize({width,height:1000});await p.goto(base+url);await p.waitForTimeout(1100);await p.evaluate(async()=>{for(const i of document.querySelectorAll('img[loading="lazy"]'))i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});await p.screenshot({path:'/tmp/vector-'+name+'.png',fullPage:true});}
console.log(JSON.stringify({checks:results.length,failures,interactions:'Mobile menu, Escape, keyboard demo, reduced motion, no-JS passed'},null,2));fs.writeFileSync('/tmp/vector-browser-results.json',JSON.stringify({base,results,failures},null,2));await b.close();if(failures.length)process.exit(1);})().catch(e=>{console.error(e);process.exit(1)});
